#---
#- hosts: appsrvs
#  remote_user: root
#
#  tasks:
  - name: judge process of mdmoc whether exists
    shell: ps aux |grep YulMdService
    ignore_errors: True
    register: result
#  - name: debug
#    debug: var=result
  - name: remove nohup.out
    file: path=/home/mdmoc/YulMdService/nohup.out state=absent
  - name: remove trace.log
    file: path=/home/mdmoc/YulMdService/trace.log state=absent
  - name: start mdmoc
    script: mdrun.sh chdir=/home/mdmoc/YulMdService 
    register: result1
    until: result1.stdout.find("nohup") != -1
    retries: 5
    delay: 2
    ignore_errors: True
    when: result.stdout.find('./YulMdService') ==-1
  - name: judge process of mdmoc whether exists again
    shell: ps aux | grep YulMdService
    ignore_errors: True
    register: result
  - name: mdmoc is started
    debug: var=result
